sudo: false
dist: xenial

arch:
  - amd64
  - ppc64le
  - arm64

cache:
  apt: true

language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - perl
      - pandoc
      - libevent-dev
      - libhwloc-dev

env:
    global:
        - AM_MAKEFLAGS="-j4"
        - PRRTE_PREFIX="$HOME/bogus"
        - PRRTE_CONFIGURE_ARGS="--prefix=$PRRTE_PREFIX"
        - DISTCHECK_CONFIGURE_FLAGS="$PRRTE_CONFIGURE_ARGS --disable-dlopen"

jobs:
  fast_finish: true
  include:
    - compiler: gcc
      env:
        - CFLAGS="-Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-type-limits -Wno-missing-field-initializers -Wno-sign-compare -Wno-missing-braces"
          ENABLE_WERROR="--enable-werror"
    - compiler: gcc
      env:
        - CFLAGS="-fsanitize=undefined"  # TODO: add -fsanitize=address
    - compiler: clang
      env:
        - CFLAGS="-Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-type-limits -Wno-missing-field-initializers -Wno-sign-compare -Wno-missing-braces"
          ENABLE_WERROR="--enable-werror"
    # TODO:
    #- compiler: clang
    #  env:
    #    - CFLAGS="-fsanitize=address"
    #      ASAN_OPTIONS=detect_stack_use_after_return=1:detect_leaks=1:check_initialization_order=true:strict_init_order=true:detect_stack_use_after_scope=1
    - compiler: clang
      env:
        - CFLAGS="-fsanitize=undefined"

script:
        # prepare
        - env
        - cat /proc/cpuinfo
        - grep Cpus_allowed_list /proc/self/status
        # build
        - ./autogen.pl
        - pip install -q cython
        - ./configure ${ENABLE_WERROR}
        - if [ $? -ne 0 ]; then cat config.log; fi
        - if [ $TRAVIS_ARCH == "amd64" ]; then export AM_MAKEFLAGS=-j4; make -j 4 all; elif [ $TRAVIS_ARCH == "arm64" ]; then export AM_MAKEFLAGS=-j32; make -j 32 all; elif [ $TRAVIS_ARCH  == "ppc64le" ]; then export AM_MAKEFLAGS=-j16; make -j 16 all; fi
        - make all
        # test
        - if [ $TRAVIS_ARCH == "amd64" ]; then export AM_MAKEFLAGS=-j4; make -j 4 distcheck; elif [ $TRAVIS_ARCH == "arm64" ]; then export AM_MAKEFLAGS=-j32; make -j 32 distcheck; elif [ $TRAVIS_ARCH  == "ppc64le" ]; then export AM_MAKEFLAGS=-j16; make -j 16 distcheck; fi
